service:
  name: brn-nextjs-boilerplate-blog-markdown

myNextAppplication:
  component: "@sls-next/serverless-component@1.18.0"
  inputs:
    domain: ["markdown-blog-nextjs-boilerplate", "onbrn.com"]
    build:
      env:
        NODE_PATH: "/"
        API_URL: "https://markdown-blog-nextjs-boilerplate.onbrn.com"
